databases:
  - name: learning-center-db
    plan: free
    region: singapore

services:
  - type: web
    name: learning-center-ninhtrang
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://learning-center-ninhtrang.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: { name: learning-center-db, property: host }
      - key: DB_PORT
        fromDatabase: { name: learning-center-db, property: port }
      - key: DB_DATABASE
        fromDatabase: { name: learning-center-db, property: database }
      - key: DB_USERNAME
        fromDatabase: { name: learning-center-db, property: user }
      - key: DB_PASSWORD
        fromDatabase: { name: learning-center-db, property: password }
      - key: AUTORUN_ENABLED
        value: "true"
      - key: AUTORUN_LARAVEL_MIGRATION
        value: "true"
      - key: AUTORUN_LARAVEL_CONFIG_CACHE
        value: "true"
